### ISSUE TITLE
AssertionError: Missing string id : editBox

### ISSUE THREAD

**Issue by fanshu-520** [cnyvfang/labelGo-Yolov5AutoLabelImg#10]
(yolo) C:\Users\z249\Desktop\labelGo-Yolov5AutoLabelImg-master>python labelGo.py
Traceback (most recent call last):
  File "labelGo.py", line 1744, in <module>
    sys.exit(main())
  File "labelGo.py", line 1738, in main
    app, _win = get_main_app(sys.argv)
  File "labelGo.py", line 1729, in get_main_app
    win = MainWindow(args.image_dir,
  File "labelGo.py", line 281, in __init__
    edit_mode = action(get_str('editBox'), self.set_edit_mode,
  File "labelGo.py", line 97, in <lambda>
    get_str = lambda str_id: self.string_bundle.get_string(str_id)
  File "C:\Users\z249\Desktop\labelGo-Yolov5AutoLabelImg-master\libs\stringBundle.py", line 47, in get_string
    assert(string_id in self.id_to_message), "Missing string id : " + string_id
AssertionError: Missing string id : editBox

**Comment by ake020675** [comment]
Caused by strings-zh-CN in stringBundle.py. No problem with default config(English)

**Comment by darrenzhang1007** [comment]
It`s worked, Thanks

> Caused by strings-zh-CN in stringBundle.py. No problem with default config(English)
