### ISSUE TITLE
运行 python labelGo.py 的时候出现以下错误，所有的包都已经成功安装了

### ISSUE THREAD

**Issue by XuechengWu** [cnyvfang/labelGo-Yolov5AutoLabelImg#15]
报错如下
```
Traceback (most recent call last):
  File "labelGo.py", line 1744, in <module>
    sys.exit(main())
  File "labelGo.py", line 1738, in main
    app, _win = get_main_app(sys.argv)
  File "labelGo.py", line 1729, in get_main_app
    win = MainWindow(args.image_dir,
  File "labelGo.py", line 281, in __init__
    edit_mode = action(get_str('editBox'), self.set_edit_mode,
  File "labelGo.py", line 97, in <lambda>
    get_str = lambda str_id: self.string_bundle.get_string(str_id)
  File "D:\AnnotationsTools\labelGo-Yolov5AutoLabelImg-master\libs\stringBundle.py", line 47, in get_string
    assert(string_id in self.id_to_message), "Missing string id : " + string_id
AssertionError: Missing string id : editBox
```
请问如何解决？或者能通过docker安装吗？

**Comment by wfm777** [comment]
我也出这个问题了，求解

**Comment by wfm777** [comment]
找到了，是不是使用中文格式了，使用英文格式就可以运行了，吧stringBundle.py里面52行给打开吧54行给注释掉试一下

**Comment by XuechengWu** [comment]
问题解决步骤：
1. 换回英文模式，即：将stringBundle.py里面52行给打开，54行给注释掉；
2. 使用Anaconda新建一个环境；
3. 打开Anacenda Prompt(新建的环境)；
4. 转到 labelGo 所在的文件路径；
5. 依次运行install命令、requirements安装命令和python LabelGo.py 的运行命令。
