### ISSUE TITLE
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' 

### ISSUE THREAD

**Issue by quest-X** [cnyvfang/labelGo-Yolov5AutoLabelImg#23]
Traceback (most recent call last):
  File "labelGo.py", line 1388, in auto_label
    run(**vars(opt))
  File "C:\Users\Law\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Law\Desktop\labelGo-Yolov5AutoLabelImg-master\libs\autoLabeler.py", line 61, in run
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "C:\Users\Law\Desktop\labelGo-Yolov5AutoLabelImg-master\libs\models\experimental.py", line 96, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "C:\Users\Law\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Law\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "C:\Users\Law\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from 'C:\\Users\\Law\\Desktop\\labelGo-Yolov5AutoLabelImg-master\\libs\\models\\yolo.py'>

**Comment by zerolvpengfei** [comment]
我也是同样的问题，拟解决了嘛

**Comment by quest-X** [comment]
> 我也是同样的问题，拟解决了嘛

朋友你好，问题已经解决了，请参照@XuHandsome这位朋友的方法：https://github.com/cnyvfang/labelGo-Yolov5AutoLabelImg/issues/20#issuecomment-1296274279
