### ISSUE TITLE
erro yolopy

### ISSUE THREAD

**Issue by Allmight0000** [cnyvfang/labelGo-Yolov5AutoLabelImg#36]
Traceback (most recent call last):
  File "C:\Users\Administrator\labelGo-Yolov5AutoLabelImg\labelGo.py", line 1388, in auto_label
    run(**vars(opt))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Administrator\labelGo-Yolov5AutoLabelImg\libs\autoLabeler.py", line 61, in run
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "C:\Users\Administrator\labelGo-Yolov5AutoLabelImg\libs\models\experimental.py", line 96, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from 'C:\\Users\\Administrator\\labelGo-Yolov5AutoLabelImg\\libs\\models\\yolo.py'>

**Comment by H-Y-P** [comment]
去YOLOV5的utils里面找到这个DetectionModel和相关的复制到自己的文件里面就行
