### ISSUE TITLE
在IDE运行python label.py遇到无法加载模型

### ISSUE THREAD

**Issue by 2575156125** [cnyvfang/labelGo-Yolov5AutoLabelImg#37]

**Comment by 2575156125** [comment]
`Traceback (most recent call last):
  File "labelGo.py", line 1744, in <module>
    sys.exit(main())
  File "labelGo.py", line 1738, in main
    app, _win = get_main_app(sys.argv)
  File "labelGo.py", line 1731, in get_main_app
    args.save_dir)
    edit_mode = action(get_str('editBox'), self.set_edit_mode,
  File "labelGo.py", line 97, in <lambda>
    get_str = lambda str_id: self.string_bundle.get_string(str_id)
  File "F:\1project\1python_project\labelGo-Yolov5AutoLabelImg-master\libs\stringBundle.py", line 47, in get_string
    assert(string_id in self.id_to_message), "Missing string id : " + string_id
AssertionError: Missing string id : editBox

(labelGo) F:\1project\1python_project\labelGo-Yolov5AutoLabelImg-master>python labelGo.py

(labelGo) F:\1project\1python_project\labelGo-Yolov5AutoLabelImg-master>python labelGo.py
Traceback (most recent call last):
  File "labelGo.py", line 1744, in <module>
    sys.exit(main())
  File "labelGo.py", line 1738, in main
    app, _win = get_main_app(sys.argv)
  File "labelGo.py", line 1731, in get_main_app
    args.save_dir)
  File "labelGo.py", line 281, in __init__
    edit_mode = action(get_str('editBox'), self.set_edit_mode,
  File "labelGo.py", line 97, in <lambda>
    get_str = lambda str_id: self.string_bundle.get_string(str_id)
  File "F:\1project\1python_project\labelGo-Yolov5AutoLabelImg-master\libs\stringBundle.py", line 47, in get_string
    assert(string_id in self.id_to_message), "Missing string id : " + string_id
AssertionError: Missing string id : editBox

(labelGo) F:\1project\1python_project\labelGo-Yolov5AutoLabelImg-master>python labelGo.py
Traceback (most recent call last):
  File "labelGo.py", line 1744, in <module>
    sys.exit(main())
  File "labelGo.py", line 1738, in main
    app, _win = get_main_app(sys.argv)
  File "labelGo.py", line 1731, in get_main_app
    args.save_dir)
  File "labelGo.py", line 281, in __init__
    edit_mode = action(get_str('editBox'), self.set_edit_mode,
  File "labelGo.py", line 97, in <lambda>
    get_str = lambda str_id: self.string_bundle.get_string(str_id)
  File "F:\1project\1python_project\labelGo-Yolov5AutoLabelImg-master\libs\stringBundle.py", line 47, in get_string
    assert(string_id in self.id_to_message), "Missing string id : " + string_id
AssertionError: Missing string id : editBox

(labelGo) F:\1project\1python_project\labelGo-Yolov5AutoLabelImg-master>python labelGo.py
Image:F:\1project\1python_project\k210\k210\maix_train-master\data\train\bad\0.jpg -> Annotation:F:/1project/1python_project/k210/k210/maix_train-master/data/labeal/0.xml.txt
Image:F:\1project\1python_project\k210\k210\maix_train-master\data\train\bad\0.jpg -> Annotation:F:\1project\1python_project\k210\k210\maix_train-master\data\train\bad\0.txt
YOLOv5  2023-6-22 torch 1.13.1+cpu CPU

Traceback (most recent call last):
  File "labelGo.py", line 1388, in auto_label
    run(**vars(opt))
  File "C:\ProgramData\Anaconda3\envs\labelGo\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\1project\1python_project\labelGo-Yolov5AutoLabelImg-master\libs\autoLabeler.py", line 61, in run
    model = attempt_load(weights, map_location=device)  # load FP32 model
  File "F:\1project\1python_project\labelGo-Yolov5AutoLabelImg-master\libs\models\experimental.py", line 96, in attempt_load
    ckpt = to`

**Comment by 2575156125** [comment]
具体的报错信息
