### ISSUE TITLE
中文支持有问题

### ISSUE THREAD

**Issue by Iceprism** [cnyvfang/labelGo-Yolov5AutoLabelImg#6]
按照说明完成安装，环境conda的python3.8
正常运行英文版成功。
改中文版出现问题：
编辑文件\libs\stringBundle.py的第52行，
将字符串":/strings"替换为":/strings-zh-CN"即可。
最后再次运行后报错
`Traceback (most recent call last):
  File "labelGo.py", line 1744, in <module>
    sys.exit(main())
  File "labelGo.py", line 1738, in main
    app, _win = get_main_app(sys.argv)
  File "labelGo.py", line 1729, in get_main_app
    win = MainWindow(args.image_dir,
  File "labelGo.py", line 281, in __init__
    edit_mode = action(get_str('editBox'), self.set_edit_mode,
  File "labelGo.py", line 97, in <lambda>
    get_str = lambda str_id: self.string_bundle.get_string(str_id)
  File "D:\SynologyDrive\*********\labelGo-Yolov5AutoLabelImg\libs\stringBundle.py", line 47, in get_string
    assert(string_id in self.id_to_message), "Missing string id : " + string_id
AssertionError: Missing string id : editBox`

**Comment by Iceprism** [comment]
debug了，提交了Pull requests
