### ISSUE TITLE
RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256

### ISSUE THREAD

**Issue by XJunho** [cnyvfang/labelGo-Yolov5AutoLabelImg#8]
您好，在使用自动标注功能时，我使用了自己的yolo模型后然后出现了这个问题。
网上也查找了各种原因，但是目前还是无法解决，我也修改了nc为自己的class数，不知道我是否应该修改您代码某些地方的参数，特此请教。

> image 1/288 E:\git\Git\Project\yolov5\data\mydataset\images\test\crop001501.png: Traceback (most recent call last):
  File ".\labelGo.py", line 1388, in auto_label
    run(**vars(opt))
  File "E:\anaconda\envs\labeltool\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\git\Git\Project\labelGo-Yolov5AutoLabelImg\libs\autoLabeler.py", line 105, in run
    pred = model(img, augment=augment, visualize=visualize)[0]
  File "E:\anaconda\envs\labeltool\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\git/Git/Project/labelGo-Yolov5AutoLabelImg/libs\models\yolo.py", line 117, in forward
    return self.forward_once(x, profile, visualize)  # single-scale inference, train
  File "E:\git/Git/Project/labelGo-Yolov5AutoLabelImg/libs\models\yolo.py", line 148, in forward_once
    x = m(x)  # run
  File "E:\anaconda\envs\labeltool\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\git/Git/Project/labelGo-Yolov5AutoLabelImg/libs\models\yolo.py", line 61, in forward
    wh = (y[..., 2:4] * 2) ** 2 * self.anchor_grid[i].view(1, self.na, 1, 1, 2)  # wh
RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256

**Comment by XJunho** [comment]
是yolov5内容更新的问题，替换部分代码为yolov5最新的代码就可以解决了

**Comment by User-Vannnn** [comment]
我也遇到了这个错误，我的改动是将yolo.py文件重新替换为yolov5官方的yolo.py文件
然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' object has no attribute 'info'的错误
此时将yolo.py中228行的fuse函数中的 LOGGER.info('Fusing layers... ') 这一句注释掉重新运行即可

**Comment by JerryHao-art** [comment]
> 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' obj

> 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' object has no attribute 'info'的错误 此时将yolo.py中277行的fuse函数中的 LOGGER.info('Fusing layers... ') 这一句注释掉重新运行即可

请问是把文件整体替换还是替换一部分

**Comment by JerryHao-art** [comment]
> 是yolov5内容更新的问题，替换部分代码为yolov5最新的代码就可以解决了

请问是替换的哪一部分呢

**Comment by User-Vannnn** [comment]
> > 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' obj
> 
> > 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' object has no attribute 'info'的错误 此时将yolo.py中277行的fuse函数中的 LOGGER.info('Fusing layers... ') 这一句注释掉重新运行即可
> 
> 请问是把文件整体替换还是替换一部分

我是将整个yolo.py文件都替换了

**Comment by User-Vannnn** [comment]
这是我的python编译器环境，参考博客--https://blog.csdn.net/qq_45724346/article/details/119759828

----------------------------------------------------
labelgo标注完成截图：



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cnyvfang/labelGo-Yolov5AutoLabelImg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月28日(星期二) 晚上6:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8)





    
我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' obj
   
我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' object has no attribute 'info'的错误 此时将yolo.py中277行的fuse函数中的 LOGGER.info('Fusing layers... ') 这一句注释掉重新运行即可
  
请问是把文件整体替换还是替换一部分
  
我是将整个yolo.py文件都替换了
 ***@***.***。非常感谢

**Comment by JerryHao-art** [comment]
> 这是我的python编译器环境，参考博客--https://blog.csdn.net/qq_45724346/article/details/119759828
> […](#)
> ---------------------------------------------------- labelgo标注完成截图：
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cnyvfang/labelGo-Yolov5AutoLabelImg" ***@***.***&gt;; 发送时间:&nbsp;2022年6月28日(星期二) 晚上6:43 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8) 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' obj 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' object has no attribute 'info'的错误 此时将yolo.py中277行的fuse函数中的 LOGGER.info('Fusing layers... ') 这一句注释掉重新运行即可 请问是把文件整体替换还是替换一部分 我是将整个yolo.py文件都替换了 ***@***.***。非常感谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

再打扰一下，往被标注的数据集里面放的class.txt文件是空白文件还是有需要被标注的类，非常感谢

**Comment by User-Vannnn** [comment]
classes.txt需要自己创建，然后把模型对应的类写进去，运行程序不会改动你的classes.txt




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cnyvfang/labelGo-Yolov5AutoLabelImg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月28日(星期二) 晚上7:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8)





  
这是我的python编译器环境，参考博客--https://blog.csdn.net/qq_45724346/article/details/119759828
 …
 ---------------------------------------------------- labelgo标注完成截图：
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cnyvfang/labelGo-Yolov5AutoLabelImg" @.&gt;; 发送时间:&nbsp;2022年6月28日(星期二) 晚上6:43 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8) 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' obj 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' object has no attribute 'info'的错误 此时将yolo.py中277行的fuse函数中的 LOGGER.info('Fusing layers... ') 这一句注释掉重新运行即可 请问是把文件整体替换还是替换一部分 我是将整个yolo.py文件都替换了 @.。非常感谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt;
  
再打扰一下，往被标注的数据集里面放的class.txt文件是空白文件还是有需要被标注的类，非常感谢

**Comment by JerryHao-art** [comment]
> classes.txt需要自己创建，然后把模型对应的类写进去，运行程序不会改动你的classes.txt
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cnyvfang/labelGo-Yolov5AutoLabelImg" ***@***.***&gt;; 发送时间:&nbsp;2022年6月28日(星期二) 晚上7:29 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8) 这是我的python编译器环境，参考博客--https://blog.csdn.net/qq_45724346/article/details/119759828 … ---------------------------------------------------- labelgo标注完成截图： ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cnyvfang/labelGo-Yolov5AutoLabelImg" @.&gt;; 发送时间:&nbsp;2022年6月28日(星期二) 晚上6:43 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8) 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' obj 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' object has no attribute 'info'的错误 此时将yolo.py中277行的fuse函数中的 LOGGER.info('Fusing layers... ') 这一句注释掉重新运行即可 请问是把文件整体替换还是替换一部分 我是将整个yolo.py文件都替换了 @.。非常感谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 再打扰一下，往被标注的数据集里面放的class.txt文件是空白文件还是有需要被标注的类，非常感谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

问题已解决，非常感谢！！！

**Comment by duyao666** [comment]
> classes.txt需要自己创建，然后把模型对应的类写进去，运行程序不会改动你的classes.txt
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cnyvfang/labelGo-Yolov5AutoLabelImg" ***@***.***&gt;; 发送时间:&nbsp;2022年6月28日(星期二) 晚上7:29 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8) 这是我的python编译器环境，参考博客--https://blog.csdn.net/qq_45724346/article/details/119759828 … ---------------------------------------------------- labelgo标注完成截图： ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cnyvfang/labelGo-Yolov5AutoLabelImg" @.&gt;; 发送时间:&nbsp;2022年6月28日(星期二) 晚上6:43 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8) 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' obj 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' object has no attribute 'info'的错误 此时将yolo.py中277行的fuse函数中的 LOGGER.info('Fusing layers... ') 这一句注释掉重新运行即可 请问是把文件整体替换还是替换一部分 我是将整个yolo.py文件都替换了 @.。非常感谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 再打扰一下，往被标注的数据集里面放的class.txt文件是空白文件还是有需要被标注的类，非常感谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我运行程序没有修改，但是我要修改标签的时候，他默认改了classes.txt文件，然后报错
label = self.classes[int(class_index)]
IndexError: list index out of range

**Comment by ismoyuai** [comment]
> 我也遇到了这个错误，我的改动是将yolo.py文件重新替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' object has no attribute 'info'的错误 此时将yolo.py中228行的fuse函数中的 LOGGER.info('Fusing layers... ') 这一句注释掉重新运行即可

我将文件替换后在次进行自动标注时，出现了 ImportError: cannot import name 'LOGGER' from 'libs.detect_utils.general' 这个问题，跟您出现的问题不太一样，请问怎样解决。(我进行文件替换时还需要改一下导入包的名字，因为官方包的路径名字和这个项目里的包的路径名字不同)

**Comment by User-Vannnn** [comment]
我的改动是在general.py里面加入这几个函数（这几个函数我也没有用过，不清楚作用），但我认为不影响自动标注。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cnyvfang/labelGo-Yolov5AutoLabelImg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月8日(星期五) 下午5:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8)





  
我也遇到了这个错误，我的改动是将yolo.py文件重新替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' object has no attribute 'info'的错误 此时将yolo.py中228行的fuse函数中的 LOGGER.info('Fusing layers... ') 这一句注释掉重新运行即可
  
我将文件替换后在次进行自动标注时，出现了 ImportError: cannot import name 'LOGGER' from 'libs.detect_utils.general' 这个问题，跟您出现的问题不太一样，请问怎样解决。(我进行文件替换时还需要改一下导入包的名字，因为官方包的路径名字和这个项目里的包的路径名字不同)

**Comment by ismoyuai** [comment]
> 我的改动是在general.py里面加入这几个函数（这几个函数我也没有用过，不清楚作用），但我认为不影响自动标注。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cnyvfang/labelGo-Yolov5AutoLabelImg" ***@***.***&gt;; 发送时间:&nbsp;2022年7月8日(星期五) 下午5:18 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8) 我也遇到了这个错误，我的改动是将yolo.py文件重新替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' object has no attribute 'info'的错误 此时将yolo.py中228行的fuse函数中的 LOGGER.info('Fusing layers... ') 这一句注释掉重新运行即可 我将文件替换后在次进行自动标注时，出现了 ImportError: cannot import name 'LOGGER' from 'libs.detect_utils.general' 这个问题，跟您出现的问题不太一样，请问怎样解决。(我进行文件替换时还需要改一下导入包的名字，因为官方包的路径名字和这个项目里的包的路径名字不同) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

非常感谢，之前出现问题是直接闪退的，现在在general.py里面加入那些报错的函数后可以自动标注了，不过标注效果比较差，不知道是工具的问题还是我这边训练的权重文件的问题。

**Comment by User-Vannnn** [comment]
你可以用你的权重检测一遍文件，对比一下检测的结果跟标注的结果，我认为应该是你的权重文件有问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cnyvfang/labelGo-Yolov5AutoLabelImg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月8日(星期五) 下午5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8)





  
我的改动是在general.py里面加入这几个函数（这几个函数我也没有用过，不清楚作用），但我认为不影响自动标注。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cnyvfang/labelGo-Yolov5AutoLabelImg" @.&gt;; 发送时间:&nbsp;2022年7月8日(星期五) 下午5:18 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8) 我也遇到了这个错误，我的改动是将yolo.py文件重新替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' object has no attribute 'info'的错误 此时将yolo.py中228行的fuse函数中的 LOGGER.info('Fusing layers... ') 这一句注释掉重新运行即可 我将文件替换后在次进行自动标注时，出现了 ImportError: cannot import name 'LOGGER' from 'libs.detect_utils.general' 这个问题，跟您出现的问题不太一样，请问怎样解决。(我进行文件替换时还需要改一下导入包的名字，因为官方包的路径名字和这个项目里的包的路径名字不同) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
非常感谢，之前出现问题是直接闪退的，现在在general.py里面加入那些报错的函数后可以自动标注了，不过标注效果比较差，不知道是工具的问题还是我这边训练的权重文件的问题。

**Comment by User-Vannnn** [comment]
你修改了data文件夹下的predefined_classes.txt中的类别跟你的classes.txt一致吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cnyvfang/labelGo-Yolov5AutoLabelImg"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月6日(星期三) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8)





  
classes.txt需要自己创建，然后把模型对应的类写进去，运行程序不会改动你的classes.txt
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cnyvfang/labelGo-Yolov5AutoLabelImg" @.&gt;; 发送时间:&nbsp;2022年6月28日(星期二) 晚上7:29 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8) 这是我的python编译器环境，参考博客--https://blog.csdn.net/qq_45724346/article/details/119759828 … ---------------------------------------------------- labelgo标注完成截图： ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "cnyvfang/labelGo-Yolov5AutoLabelImg" @.&gt;; 发送时间:&nbsp;2022年6月28日(星期二) 晚上6:43 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [cnyvfang/labelGo-Yolov5AutoLabelImg] RuntimeError: shape '[1, 3, 1, 1, 2]' is invalid for input of size 32256 (Issue #8) 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' obj 我也遇到了这个错误，我的改动是将yolo.py替换为yolov5官方的yolo.py文件 然后运行labelgo.py选择.pt权重文件进行自动标注时，遇到了AttributeError: 'function' object has no attribute 'info'的错误 此时将yolo.py中277行的fuse函数中的 LOGGER.info('Fusing layers... ') 这一句注释掉重新运行即可 请问是把文件整体替换还是替换一部分 我是将整个yolo.py文件都替换了 @.。非常感谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.&gt; 再打扰一下，往被标注的数据集里面放的class.txt文件是空白文件还是有需要被标注的类，非常感谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
我运行程序没有修改，但是我要修改标签的时候，他默认改了classes.txt文件，然后报错
 label = self.classes[int(class_index)]
 IndexError: list index out of range

**Comment by Liuruifeng29** [comment]
RuntimeError: The expanded size of the tensor (1) must match the existing size (80) at non-singleton dimension 3.  Target sizes: [1, 3, 1, 1, 2].  Tensor sizes: [3, 80, 80, 2]

有遇到这个问题的吗，换了一个权重文件就报这个错误

**Comment by tabowsy** [comment]
我也遇到一樣的換個銓重就報錯，是否跟pt的架構有差?
